{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "valitail.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "valitail.name" . }}
    chart: {{ template "valitail.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- end }}
