# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0
enabled: true

images:
  reserve-excess-capacity: europe-docker.pkg.dev/sap-se-gcp-k8s-delivery/releases-public/registry_k8s_io/pause@sha256:adafa755d1f0acb952eb9ecde0dbceec4674e8f1042d1c13b15a77f5d78c8160


replicas: 5 # each replica reserves 1 CPU and 1GB memory

resources:
  requests:
    cpu: 1000m
    memory: 1000Mi
  limits:
    cpu: 1000m
    memory: 1000Mi