{{- if gt (len .Values.alerting_groups) 0 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vali.fullname" . }}-alerting-rules
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "vali.name" . }}
    chart: {{ template "vali.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ template "vali.fullname" . }}-alerting-rules.yaml: |-
    groups:
    {{- toYaml .Values.alerting_groups | nindent 6 }}
{{- end }}