{{- if .Values.global.loggingEnabled }}
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "vali.fullname" . }}
  namespace: {{ .Values.global.loggingNamespace }}
  labels:
    app: {{ template "vali.name" . }}
    chart: {{ template "vali.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- end }}
{{- end }}
