{{- if .Values.global.loggingEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vali.fullname" . }}
  namespace: {{ .Values.global.loggingNamespace }}
  labels:
    app: {{ template "vali.name" . }}
    chart: {{ template "vali.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  vali.yaml: {{ tpl (toYaml .Values.config) . | b64enc}}
  {{- end }}
