# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testmachinery-controller
  labels:
    {{- include "defaultLabels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - namespaces
  verbs:
  - get
  - create
  - update
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - testmachinery.sapcloud.io
  resources:
  - testruns
  - testruns/status
  - testruns/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
  - deletecollection
{{if .Values.testmachinery.cleanWorkflowPods }}
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
  - deletecollection
{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: testmachinery-controller
  labels:
    {{- include "defaultLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: testmachinery-controller
subjects:
- kind: ServiceAccount
  name: {{ required ".Values.controller.serviceAccountName is required" .Values.controller.serviceAccountName }}
  namespace: {{.Release.Namespace}}
