# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# overriden in images.yaml
images:
  argoWorkflowController:
    repository: quay.io/argoproj/workflow-controller
    tag: v3.6.11
  argoExecutor:
    repository: quay.io/argoproj/argoexec
    tag: v3.6.11
  argoServer:
    repository: quay.io/argoproj/argocli
    tag: v3.6.11

argo:
  name: workflow-controller
  mainContainer:
    securityContext: {}
  executor:
    securityContext: {}
    waitContainerResources:
      requests:
        cpu: 50m
        memory: 150Mi
      limits:
        cpu: 100m
        memory: 300Mi
  resources: {}
  # requests:
  #   cpu: 200m
  #   memory: 256Mi
  # limits:
  #   cpu: 1
  #   memory: 1Gi


  logging: {}
    # if grafana is specified, default links to a given instance will be injected for both pods as well as workflow
#    grafana:
#      host: "grafana.example.com"
#      https: true
#    additionalLinks: []
#    - name: Example Workflow Link
#      scope: workflow
#      url: http://logging-facility?namespace=${metadata.namespace}&workflowName=${metadata.name}
#    - name: Example Pod Link
#      scope: pod
#      url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}
configmap:
  name: tm-config

argoserver:
  ingress:
    enabled: true
    name: "argo-server"
    host: ""
    annotations: { }
    labels: { }
  serviceType: ClusterIP

objectStorage:
  keyPrefix: "testmachinery"
  secret:
    name: "s3-secret"

workflowDefaults: {}
  # metadata:
  #   labels:
  #     foo: bar
  # spec:
  #   ...
